<?php 
function bemy_menu(){
    $items['admin/config/bemy'] = array(
        'title' => t('Bemy Custom Settings'),
        'description' => t('Bemy Custom Settings'),
        'position' => 'right',
        'weight' => 1,
        'page callback' => 'drupal_get_form',
        'page arguments' => array('bemy_admin'),
        'access arguments' => array(true),
        'file' => 'bemy.form.inc',
    );

    $items['admin/config/bemy/settings'] = array(
        'title' => t('Configurations page'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('bemy_admin'),
        'file' => 'bemy.form.inc',
        'access arguments' => array(true),
    );

    $items['test'] = array(
        'title' => t('Testing function'),
        'page callback' => 'custom_test',
        'access arguments' => array(true),
    );
    return $items;
}

function custom_test(){
   $node = node_load(70);
   if($node->type=='digital_license_product'){
        if($node->field_digital_license_product_so){
            foreach($node->field_digital_license_product_so['und'] as $file){
                echo file_load($file['fid'])->uri . "\r\n";
            }
       }
    }
   // $commerce_order->order_number
    $args = array(
    ':order_id' => 48,
    );

    $product_ids = db_query("SELECT p.commerce_product_product_id 
       FROM {commerce_line_item} li 
       JOIN {field_data_commerce_product} p ON (p.entity_id = li.line_item_id) 
       WHERE li.order_id = :order_id AND li.type = 'product'", $args)->fetchCol();
    var_dump($product_ids);die;
}

/** * Implements hook_form_alter(). */
function bemy_form_alter(&$form, &$form_state, $form_id) {
    /*
    //For already bought products by user
    $get_songs_list = views_get_view_result('product_lists_of_user','admin_page');
    $bought_songs_arr = array();
    foreach ($get_songs_list as $s){
        $bought_songs_arr[] = $s->commerce_product_field_data_commerce_product_product_id;
    }

    //Disable add to cart for already bought songs
    if ( $form_id == 'commerce_cart_add_to_cart_form_1') {
        $product_id = $form['product_id']['#value'];
        if(in_array($product_id, $bought_songs_arr)){
            $form['submit']['#disabled'] = TRUE;
            $form['submit']['#suffix'] = t('(you already bought this product)');
        }
    }

    //Disable add to cart for already bought album
    if ( $form_id == 'commerce_cart_add_to_cart_form_3') {
        $product_id = $form['product_id']['#value'];
        if(in_array($product_id, $bought_songs_arr)){
            $form['submit']['#disabled'] = TRUE;
            $form['submit']['#suffix'] = t('(you already bought this product)');
        }
    }*/
}
?>